name: BSORT Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  quality-check-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[dev]
        
    - name: ğŸ§¹ Black Formatter Check
      run: black --check bsort tests
      
    - name: ğŸ§¹ Isort Import Check
      run: isort --check-only bsort tests
      
    - name: ğŸ§ Pylint Code Analysis
      run: pylint bsort --exit-zero 
      
    - name: ğŸ§ª Unit Tests
      run: pytest tests/

  docker-build:
    needs: quality-check-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker Image
      run: docker build -t bsort:latest .
      
    - name: Verify Docker Image
      run: docker run --rm bsort:latest --help